#!/bin/bash
# Insurance Fraud Detection - Quick Commands Reference

PROJECT_DIR="/media/krishna/E41686C816869AE6/home-backup/Insurance-Fraud-Backend"

echo "📋 Insurance Fraud Detection - Quick Commands"
echo "============================================="
echo ""

# Display all key commands

echo "🔧 SETUP & VALIDATION"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# 1. Activate virtual environment"
echo "source $PROJECT_DIR/venv/bin/activate"
echo ""
echo "# 2. Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# 3. Validate system setup"
echo "python test_setup.py"
echo ""
echo "# 4. Generate sample data (if needed)"
echo "python generate_sample_data.py"
echo ""

echo "🤖 MODEL TRAINING"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# Run training pipeline"
echo "cd src && python train_model.py"
echo ""
echo "Expected output:"
echo "  - Loads insurance_data.csv"
echo "  - Preprocesses data"
echo "  - Trains 3 models (LR, RF, XGBoost)"
echo "  - Saves best model to model/ folder"
echo ""

echo "🚀 RUN API SERVER"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# Start Flask server"
echo "python app.py"
echo ""
echo "API runs at: http://localhost:5000"
echo ""

echo "📊 API ENDPOINTS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# 1. Health check"
echo "curl http://localhost:5000/health"
echo ""
echo "# 2. Get model info"
echo "curl http://localhost:5000/model-info"
echo ""
echo "# 3. Single prediction"
echo "curl -X POST http://localhost:5000/predict \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"claim_amount\": 5000, \"claimant_age\": 35, \"policy_duration_days\": 180}'"
echo ""
echo "# 4. Batch predictions"
echo "curl -X POST http://localhost:5000/predict-batch \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"records\": ["
echo "      {\"claim_amount\": 5000, \"claimant_age\": 35},"
echo "      {\"claim_amount\": 10000, \"claimant_age\": 42}"
echo "    ]"
echo "  }'"
echo ""

echo "🐍 PYTHON USAGE"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# Make predictions in Python"
echo "python << 'EOF'"
echo "from src.predict import FraudPredictor"
echo ""
echo "predictor = FraudPredictor()"
echo "result = predictor.predict({"
echo "    'claim_amount': 5000,"
echo "    'claimant_age': 35,"
echo "    'policy_duration_days': 180"
echo "})"
echo "print(result)"
echo "EOF"
echo ""

echo "📁 KEY FILES"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Code Files:"
echo "  app.py                  - Flask REST API"
echo "  src/train_model.py      - Training pipeline"
echo "  src/predict.py          - Prediction module"
echo "  src/preprocess.py       - Data preprocessing"
echo "  test_setup.py           - System validation"
echo ""
echo "Data Files:"
echo "  data/insurance_data.csv - Training data (10,000 records)"
echo "  data/vendor_data.csv    - Vendor info (600 records)"
echo ""
echo "Model Files (created after training):"
echo "  model/fraud_model.pkl        - Trained model"
echo "  model/scaler.pkl             - Feature scaler"
echo "  model/label_encoders.pkl     - Category encoders"
echo ""
echo "Documentation:"
echo "  README.md               - Full documentation"
echo "  QUICKSTART.md           - Quick setup guide"
echo "  PROJECT_STATUS.md       - Current status"
echo "  COMPLETION_REPORT.md    - Completion details"
echo ""

echo "🔄 COMPLETE WORKFLOW"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# Step 1: Setup"
echo "cd $PROJECT_DIR"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo ""
echo "# Step 2: Validate (optional)"
echo "python test_setup.py"
echo ""
echo "# Step 3: Train model"
echo "cd src && python train_model.py"
echo "cd .."
echo ""
echo "# Step 4: Start API"
echo "python app.py"
echo ""
echo "# Step 5: Make predictions (in another terminal)"
echo "curl -X POST http://localhost:5000/predict \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"claim_amount\": 5000, \"claimant_age\": 35}'"
echo ""

echo "⚙️  CUSTOM CONFIGURATION"
echo "───────────────────────────────────────────────────────"
echo ""
echo "# Use different data"
echo "cp your_data.csv data/insurance_data.csv"
echo "cd src && python train_model.py"
echo ""
echo "# Change model parameters"
echo "Edit src/train_model.py, modify train_xgboost() function"
echo ""
echo "# Adjust train/test split"
echo "Edit src/preprocess.py, modify split_data() function"
echo ""

echo "🆘 TROUBLESHOOTING"
echo "───────────────────────────────────────────────────────"
echo ""
echo "❌ ModuleNotFoundError"
echo "   → pip install -r requirements.txt"
echo ""
echo "❌ Model file not found"
echo "   → cd src && python train_model.py"
echo ""
echo "❌ API not responding"
echo "   → python app.py"
echo ""
echo "❌ Data not found"
echo "   → Ensure insurance_data.csv is in data/ folder"
echo ""

echo "📚 MORE HELP"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Read: README.md"
echo "      QUICKSTART.md"
echo "      PROJECT_REQUIREMENTS.md"
echo ""

echo "============================================="
echo "✅ System ready! Start with: python app.py"
echo ""
